### ISSUE TITLE
sendpostdatedtx throw exception

### ISSUE THREAD

**Issue by farukterzioglu** [farukterzioglu/btcwallet-posdated#13]
```
btcctl -C .\btcctl.conf --wallet sendpostdatedtx "SbXMLdnqu3g5aYF3oHyBZF6gzgqQtMDU2E" 10 1
```
```
2018-11-04 22:02:19.304 [INF] TMGR: Inserting unconfirmed transaction 1aebf78f2e4eaf3540837b6c64046d89e133e96b381e4b08675b0dd1b72ad5fe
2018-11-04 22:02:19.304 [ERR] WLLT: Notifying unmined tx notification (1aebf78f2e4eaf3540837b6c64046d89e133e96b381e4b08675b0dd1b72ad5fe) while creating notification for blocks
2018/11/04 22:02:19 http: panic serving [::1]:48018: runtime error: invalid memory address or nil pointer dereference
goroutine 69 [running]:
net/http.(*conn).serve.func1(0xc010a6c0a0)
        C:/Go/src/net/http/server.go:1746 +0xd7
panic(0xb01f40, 0x12d7e60)
        C:/Go/src/runtime/panic.go:513 +0x1c7
github.com/btcsuite/btcwallet/rpc/legacyrpc.sendPostDatedTx(0xa89680, 0xc0002c0500, 0xc000066140, 0x0, 0x0, 0xde0b20, 0xc000066140)
        D:/Go/src/github.com/btcsuite/btcwallet/rpc/legacyrpc/methods.go:1504 +0x8a
github.com/btcsuite/btcwallet/rpc/legacyrpc.lazyApplyHandler.func2(0xc00035e000, 0xc000096280, 0xc0000f87b0)
        D:/Go/src/github.com/btcsuite/btcwallet/rpc/legacyrpc/methods.go:200 +0x7a
github.com/btcsuite/btcwallet/rpc/legacyrpc.(*Server).postClientRPC(0xc00035e000, 0xddb5e0, 0xc00008e380, 0xc0000ec100)
        D:/Go/src/github.com/btcsuite/btcwallet/rpc/legacyrpc/server.go:611 +0x445
github.com/btcsuite/btcwallet/rpc/legacyrpc.NewServer.func2(0xddb5e0, 0xc00008e380, 0xc0000ec100)
        D:/Go/src/github.com/btcsuite/btcwallet/rpc/legacyrpc/server.go:129 +0x1a1
net/http.HandlerFunc.ServeHTTP(0xc000050bb0, 0xddb5e0, 0xc00008e380, 0xc0000ec100)
        C:/Go/src/net/http/server.go:1964 +0x4b
github.com/btcsuite/btcwallet/rpc/legacyrpc.throttled.func1(0xddb5e0, 0xc00008e380, 0xc0000ec100)
        D:/Go/src/github.com/btcsuite/btcwallet/rpc/legacyrpc/server.go:333 +0x1bb
net/http.HandlerFunc.ServeHTTP(0xc000100de0, 0xddb5e0, 0xc00008e380, 0xc0000ec100)
        C:/Go/src/net/http/server.go:1964 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0001008d0, 0xddb5e0, 0xc00008e380, 0xc0000ec100)
        C:/Go/src/net/http/server.go:2361 +0x12e
net/http.serverHandler.ServeHTTP(0xc00035e000, 0xddb5e0, 0xc00008e380, 0xc0000ec100)
        C:/Go/src/net/http/server.go:2741 +0xb2
net/http.(*conn).serve(0xc010a6c0a0, 0xddbee0, 0xc0000fc480)
        C:/Go/src/net/http/server.go:1847 +0x64d
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2851 +0x2fc
```

**Comment by farukterzioglu** [comment]
```
PS D:\Blockchain\bitcoin\node> btcctl -C .\btcctl.conf --wallet sendpostdatedtx "SadtpbkvW8ejRThVwiLqoZuUHPCL17vw5S" 10 1
-32603: -22: TX rejected: orphan transaction e4ba6b4923964a249729ffb156f866c0ed347f20014b87e6193d1dc20794b4b9 references outputs of unknown or fully-spent transaction 860c2b8edabf284e739f99d22307e10aeb0946990afba78a3742b16f248ce131
```
